from setuptools import setup, find_packages

setup(
    name="extractor",
    version="0.1.1",
    packages=find_packages(),
    entry_points={"console_scripts": ["extractor= extractor.cli:main"]},
    install_requires=[
        "PyYAML",
        "Click==8.1.7",
        "SQLAlchemy==1.4.31",
        "pandas==1.4.0",
        "pytest==6.2.5",
        "pytest-cov==3.0.0",
        "pylint==2.12.2",
        "pytest-dotenv==0.5.2",
        "python-dotenv==0.19.2",
        "black==22.1.0",
        "thefuzz==0.20.0",
        "pyap==0.3.1",
        "onnxruntime==1.15.0",
        "onnx==1.14.1",
        "onnxruntime-tools==1.7.0",
        "scipy==1.11.2",
        "transformers==4.33.0",
        "black==22.1.0",
        "dateparser",
        "spacy==3.2.6",
        "xx_ent_wiki_sm @ https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-3.2.0"
        "/xx_ent_wiki_sm-3.2.0.tar.gz ",
        "kafka-python==2.0.2",
        "psycopg2-binary==2.9.3",
        "pysftp==0.2.9",
        "elasticsearch==8.9.0",
        "camelot-py[cv]==0.10.1",
        "PyPDF2==2.11.1",
        "opencv-python==4.6.0.66",
        "python-stdnum==1.17",
        "pycountry==22.3.5",
    ],
    description="Extractor of information from documents and emails",
    author="Gradiant",
    author_email="hcerezo@gradiant.com",
    keywords=["extractor", "nlp"],
)
