
date_desambiguator:
  threshold_top_scores: 0.7
  dateind_file: common/configuration/date_ind_list.json

orderid_desambiguator:
  threshold_top_scores: 0.6
  penalize_vertical: 0.9 #1 doesnt penalize, less tha 1 penalizes the vertical distances

payment_desambiguator:
  threshold_top_scores: 0.7

product_desambiguator:
  #scores from 0 to 100
  minimum_score_product: 50
  minimum_score_extQual: 50 # for the parsing score
  minimum_score_extNorm: 50
  minimum_score_dimension: 60
  minimum_score_fuzzy_quality: 60 # for the desambiguation score
  useless_quality_words_for_remove:
    - saco
    - test
    - temp
    - varios
